### ISSUE TITLE
Question: Should we really use Result object in Python?

### ISSUE THREAD

**Issue by Niraj-Kamdar** [polywrap/python-client#36]
From my initial experience, doing so seems like a bad idea. Python has one of the best error handling and tracing functionalities and replacing it with anything custom results in something inferior and impacts devx.

I like raising an exception in Python and handling it properly with except and finally block when needed because using Result object causes us to lose useful traceback about the error and where it originated. 

I know we are using Result in both Rust and Typescript now, so I really want to think more before making a final decision. 

> Note: This must be done before first stable release of python-client.

**Comment by dOrgJelli** [comment]
I think we should optimize for a familiar developer experience within the various languages we build in. So if this is how it works best in Python, then I'd say we should do that.
