### ISSUE TITLE
create client config builder package

### ISSUE THREAD

**Issue by Niraj-Kamdar** [polywrap/python-client#5]

**Comment by rihp** [comment]
Using the JS client package as reference
https://github.com/polywrap/toolchain/tree/origin/packages/js/client-config-builder

**Comment by rihp** [comment]
wip here https://github.com/rihp/polywrap-python-client/tree/feat/client-config-builder

**Comment by rihp** [comment]
Updated progress and added new function for env and resolver

**Comment by rihp** [comment]
Take into account new changes in refactored js client config builder package 

https://github.com/polywrap/toolchain/commit/b2b196a81525334b67585c3850ef3ac96a5c52c5

**Comment by rihp** [comment]
All progress is visible on #54 , should be ready for final review and merged
